### ISSUE TITLE
Sorting by top grades isn't working

### ISSUE THREAD

**Issue by nico-abram** [etternagame/etterna#177]

**Comment by MinaciousGrace** [comment]
fixed(ish) by 50d0775157a361903ebc9e77195b356b8d822ad3

**Comment by PPProviden** [comment]
The grades are still shown as ??? instead of folders by AAAA/AAA/AA and so on
![2018-12-01_160123](https://user-images.githubusercontent.com/31165158/49325744-74448000-f582-11e8-9884-be35e6ea2d81.png)
