### ISSUE TITLE
Blank Screen, Hang after attempting pressing "Game Start" after building from source on MacOS Mojave.

### ISSUE THREAD

**Issue by bluebandit21** [etternagame/etterna#719]
**Describe the bug**

After building any version from 65.0 (possibly earlier versions, I have only tested that far back) to 69.0 from source on macOS Mojave(10.14.6), the application successfully launches, but hangs upon pressing "Game Start" with a black screen. Other menu items, such as the settings menu, still work.

**To Reproduce**

Build Etterna from source on macOS Mojave(10.14.6).  (The generator does not seem to matter. I tested with all three different generators, with the same result each time)
Launch the application.
Click "Game Start"

**Expected behavior**

The song selection screen should successfully open.

**Desktop (please complete the following information):**
 - OS: macOS Mojave(10.14.6)
 - Version 0.65.0 - 0.69.0 (Possibly extends to earlier versions)
 - 64bit

**Additional context**
The program does not hang if there are no song packs present in Etterna's Songs directory.
It is possible to successfully log in with an EtternaOnline account, which does not hang the program either.

Here is an lldb backtrace of the program after it hangs:

Target 0: (Etterna) stopped.
(lldb) bt all
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fff5ad6b21a libsystem_kernel.dylib`mach_msg_trap + 10
    frame #1: 0x00007fff5ad6b768 libsystem_kernel.dylib`mach_msg + 60
    frame #2: 0x00007fff2ecaf99e CoreFoundation`__CFRunLoopServiceMachPort + 328
    frame #3: 0x00007fff2ecaef0c CoreFoundation`__CFRunLoopRun + 1612
    frame #4: 0x00007fff2ecae66e CoreFoundation`CFRunLoopRunSpecific + 455
    frame #5: 0x00007fff2df0d1ab HIToolbox`RunCurrentEventLoopInMode + 292
    frame #6: 0x00007fff2df0cee5 HIToolbox`ReceiveNextEventCommon + 603
    frame #7: 0x00007fff2df0cc76 HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 64
    frame #8: 0x00007fff2c2a477d AppKit`_DPSNextEvent + 1135
    frame #9: 0x00007fff2c2a346b AppKit`-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
    frame #10: 0x00007fff2c29d588 AppKit`-[NSApplication run] + 699
    frame #11: 0x00000001006655a3 Etterna`main + 1603
    frame #12: 0x00007fff5ac363d5 libdyld.dylib`start + 1
  thread #3
    frame #0: 0x00007fff5ad6cbfa libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff5ae296e6 libsystem_pthread.dylib`_pthread_wqthread + 634
    frame #2: 0x00007fff5ae293fd libsystem_pthread.dylib`start_wqthread + 13
  thread #4
    frame #0: 0x00007fff5ad6cbfa libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff5ae296e6 libsystem_pthread.dylib`_pthread_wqthread + 634
    frame #2: 0x00007fff5ae293fd libsystem_pthread.dylib`start_wqthread + 13
  thread #5
    frame #0: 0x00007fff5ad6df02 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x00007fff5ae2ad52 libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_wait + 96
    frame #2: 0x00007fff5ae284cd libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_slow + 222
    frame #3: 0x000000010065e3a2 Etterna`MutexImpl_Pthreads::Lock() + 18
    frame #4: 0x0000000100613058 Etterna`RageMutex::Lock() + 56
    frame #5: 0x000000010065c0b2 Etterna`RageSoundDriver::Update() + 34
    frame #6: 0x0000000100116e7f Etterna`GameLoop::RunGameLoop() + 3567
    frame #7: 0x000000010011d2e2 Etterna`sm_main + 7474
    frame #8: 0x0000000100664922 Etterna`-[SMMain startGame:] + 18
    frame #9: 0x00007fff30f0a0e2 Foundation`__NSThread__start__ + 1194
    frame #10: 0x00007fff5ae2a2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #11: 0x00007fff5ae2d249 libsystem_pthread.dylib`_pthread_start + 66
    frame #12: 0x00007fff5ae2940d libsystem_pthread.dylib`thread_start + 13
  thread #6, name = 'com.apple.NSEventThread'
    frame #0: 0x00007fff5ad6b21a libsystem_kernel.dylib`mach_msg_trap + 10
    frame #1: 0x00007fff5ad6b768 libsystem_kernel.dylib`mach_msg + 60
    frame #2: 0x00007fff2ecaf99e CoreFoundation`__CFRunLoopServiceMachPort + 328
    frame #3: 0x00007fff2ecaef0c CoreFoundation`__CFRunLoopRun + 1612
    frame #4: 0x00007fff2ecae66e CoreFoundation`CFRunLoopRunSpecific + 455
    frame #5: 0x00007fff2c2ac4a2 AppKit`_NSEventThread + 175
    frame #6: 0x00007fff5ae2a2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #7: 0x00007fff5ae2d249 libsystem_pthread.dylib`_pthread_start + 66
    frame #8: 0x00007fff5ae2940d libsystem_pthread.dylib`thread_start + 13
  thread #7
    frame #0: 0x00007fff5ad6e866 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff5ae2d56e libsystem_pthread.dylib`_pthread_cond_wait + 722
    frame #2: 0x00007fff57e67b31 libc++.1.dylib`std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 93
    frame #3: 0x0000000100676b7e Etterna`IoThreadHolder::Start()::'lambda'()::operator()() const + 174
    frame #4: 0x0000000100676a5d Etterna`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, IoThreadHolder::Start()::'lambda'()> >(void*) + 45
    frame #5: 0x00007fff5ae2a2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #6: 0x00007fff5ae2d249 libsystem_pthread.dylib`_pthread_start + 66
    frame #7: 0x00007fff5ae2940d libsystem_pthread.dylib`thread_start + 13
  thread #9
    frame #0: 0x00007fff5ad6df02 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x00007fff5ae2ad52 libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_wait + 96
    frame #2: 0x00007fff5ae284cd libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_slow + 222
    frame #3: 0x000000010065e3a2 Etterna`MutexImpl_Pthreads::Lock() + 18
    frame #4: 0x0000000100613058 Etterna`RageMutex::Lock() + 56
    frame #5: 0x000000010062f7ca Etterna`RageSoundReader_ThreadedBuffer::GetStreamToSourceRatio() const + 26
    frame #6: 0x000000010062e1d9 Etterna`RageSoundReader_SpeedChange::GetStreamToSourceRatio() const + 473
    frame #7: 0x000000010062bba3 Etterna`RageSoundReader_Resample_Good::GetStreamToSourceRatio() const + 19
    frame #8: 0x0000000100620165 Etterna`RageSoundReader::RetriedRead(float*, int, int*, float*) + 85
    frame #9: 0x000000010061aef3 Etterna`RageSound::GetDataToPlay(float*, int, long long&, int&) + 179
    frame #10: 0x000000010065b801 Etterna`RageSoundDriver::DecodeThread() + 353
    frame #11: 0x000000010065b699 Etterna`RageSoundDriver::DecodeThread_start(void*) + 9
    frame #12: 0x000000010065e21a Etterna`StartThread(void*) + 42
    frame #13: 0x00007fff5ae2a2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #14: 0x00007fff5ae2d249 libsystem_pthread.dylib`_pthread_start + 66
    frame #15: 0x00007fff5ae2940d libsystem_pthread.dylib`thread_start + 13
  thread #10, name = 'com.apple.audio.IOThread.client'
    frame #0: 0x00007fff5ad6b21a libsystem_kernel.dylib`mach_msg_trap + 10
    frame #1: 0x00007fff5ad6b768 libsystem_kernel.dylib`mach_msg + 60
    frame #2: 0x00007fff2e71eeda CoreAudio`HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 122
    frame #3: 0x00007fff2e71ee4f CoreAudio`HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
    frame #4: 0x00007fff2e71b39f CoreAudio`HALC_ProxyIOContext::IOWorkLoop() + 1017
    frame #5: 0x00007fff2e71adf4 CoreAudio`HALC_ProxyIOContext::IOThreadEntry(void*) + 122
    frame #6: 0x00007fff2e71a956 CoreAudio`HALB_IOThread::Entry(void*) + 72
    frame #7: 0x00007fff5ae2a2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #8: 0x00007fff5ae2d249 libsystem_pthread.dylib`_pthread_start + 66
    frame #9: 0x00007fff5ae2940d libsystem_pthread.dylib`thread_start + 13
  thread #11
    frame #0: 0x00007fff5ad6e866 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff5ae2d56e libsystem_pthread.dylib`_pthread_cond_wait + 722
    frame #2: 0x000000010065e7fd Etterna`EventImpl_Pthreads::Wait(RageTimer*) + 189
    frame #3: 0x00000001006138ce Etterna`RageEvent::Wait(RageTimer*) + 62
    frame #4: 0x00000001004175d7 Etterna`MusicThread_start(void*) + 87
    frame #5: 0x000000010065e21a Etterna`StartThread(void*) + 42
    frame #6: 0x00007fff5ae2a2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #7: 0x00007fff5ae2d249 libsystem_pthread.dylib`_pthread_start + 66
    frame #8: 0x00007fff5ae2940d libsystem_pthread.dylib`thread_start + 13
  thread #12
    frame #0: 0x00007fff5ad6cbfa libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff5ae29636 libsystem_pthread.dylib`_pthread_wqthread + 458
    frame #2: 0x00007fff5ae293fd libsystem_pthread.dylib`start_wqthread + 13
  thread #13
    frame #0: 0x00007fff5ad6e866 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff5ae2d56e libsystem_pthread.dylib`_pthread_cond_wait + 722
    frame #2: 0x00000001004ce07b Etterna`asio::detail::scheduler::do_run_one(asio::detail::conditionally_enabled_mutex::scoped_lock&, asio::detail::scheduler_thread_info&, std::__1::error_code const&) + 475
    frame #3: 0x00000001004cdcd2 Etterna`asio::detail::scheduler::run(std::__1::error_code&) + 194
    frame #4: 0x00000001004cdb8b Etterna`asio::detail::resolver_service_base::work_io_context_runner::operator()() + 43
    frame #5: 0x00000001004cdb20 Etterna`asio_detail_posix_thread_function + 16
    frame #6: 0x00007fff5ae2a2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #7: 0x00007fff5ae2d249 libsystem_pthread.dylib`_pthread_start + 66
    frame #8: 0x00007fff5ae2940d libsystem_pthread.dylib`thread_start + 13
  thread #14
    frame #0: 0x00007fff5ad7178a libsystem_kernel.dylib`kevent + 10
    frame #1: 0x00000001004ce61e Etterna`asio::detail::kqueue_reactor::run(long, asio::detail::op_queue<asio::detail::scheduler_operation>&) + 270
    frame #2: 0x00000001004cdf8c Etterna`asio::detail::scheduler::do_run_one(asio::detail::conditionally_enabled_mutex::scoped_lock&, asio::detail::scheduler_thread_info&, std::__1::error_code const&) + 236
    frame #3: 0x00000001004cdcd2 Etterna`asio::detail::scheduler::run(std::__1::error_code&) + 194
    frame #4: 0x000000010052078f Etterna`websocketpp::transport::asio::endpoint<websocketpp::config::asio_client::transport_config>::run() + 47
    frame #5: 0x00000001005206dd Etterna`void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ETTProtocol::Connect(NetworkSyncManager*, unsigned short, StdString::CStdStr<char>)::$_6> >(void*) + 45
    frame #6: 0x00007fff5ae2a2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #7: 0x00007fff5ae2d249 libsystem_pthread.dylib`_pthread_start + 66
    frame #8: 0x00007fff5ae2940d libsystem_pthread.dylib`thread_start + 13
  thread #15
    frame #0: 0x00007fff5ad6b21a libsystem_kernel.dylib`mach_msg_trap + 10
    frame #1: 0x00007fff5ad6b768 libsystem_kernel.dylib`mach_msg + 60
    frame #2: 0x00007fff2ecaf99e CoreFoundation`__CFRunLoopServiceMachPort + 328
    frame #3: 0x00007fff2ecaef0c CoreFoundation`__CFRunLoopRun + 1612
    frame #4: 0x00007fff2ecae66e CoreFoundation`CFRunLoopRunSpecific + 455
    frame #5: 0x00007fff2ecae482 CoreFoundation`CFRunLoopRun + 40
    frame #6: 0x000000010064e004 Etterna`InputHandler_MacOSX_HID::Run(void*) + 372
    frame #7: 0x000000010065e21a Etterna`StartThread(void*) + 42
    frame #8: 0x00007fff5ae2a2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #9: 0x00007fff5ae2d249 libsystem_pthread.dylib`_pthread_start + 66
    frame #10: 0x00007fff5ae2940d libsystem_pthread.dylib`thread_start + 13
  thread #17
    frame #0: 0x00007fff5ad6cbfa libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff5ae296e6 libsystem_pthread.dylib`_pthread_wqthread + 634
    frame #2: 0x00007fff5ae293fd libsystem_pthread.dylib`start_wqthread + 13
  thread #18
    frame #0: 0x00007fff5ad6cbfa libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff5ae29636 libsystem_pthread.dylib`_pthread_wqthread + 458
    frame #2: 0x00007fff5ae293fd libsystem_pthread.dylib`start_wqthread + 13
  thread #19
    frame #0: 0x00007fff5ad6b1f6 libsystem_kernel.dylib`thread_self_trap + 10
    frame #1: 0x000000010065f119 Etterna`GetCurrentThreadId() + 9
    frame #2: 0x000000010061359f Etterna`RageMutex::IsLockedByThisThread() const + 15
    frame #3: 0x00000001006138a3 Etterna`RageEvent::Wait(RageTimer*) + 19
    frame #4: 0x000000010062facf Etterna`RageSoundReader_ThreadedBuffer::BufferingThread() + 415
    frame #5: 0x000000010062ee69 Etterna`RageSoundReader_ThreadedBuffer::StartBufferingThread(void*) + 9
    frame #6: 0x000000010065e21a Etterna`StartThread(void*) + 42
    frame #7: 0x00007fff5ae2a2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #8: 0x00007fff5ae2d249 libsystem_pthread.dylib`_pthread_start + 66
    frame #9: 0x00007fff5ae2940d libsystem_pthread.dylib`thread_start + 13
(lldb)

**Comment by bluebandit21** [comment]
After some further testing, I've noticed that the game doesn't hang if there's nothing within the Songs directory.

**Comment by poco0317** [comment]
There is apparently some not fully identified issue on Mac/Unix where playing song audio or logging in immediately crashes the game. Not quite sure what the cause is yet.

**Comment by bluebandit21** [comment]
I am able to successfully log in with my Etterna account, if there are no songs present.

**Comment by bluebandit21** [comment]
Through further testing, it only appears to hang after trying to play the preview audio of a song -- being in the song selection screen with the cursor over the name of a pack doesn't hang.

**Comment by MinaciousGrace** [comment]
it's possible that this is an issue with the equalizer, have you built and run successfully on 0.68? 

if so it's probably not the visualizer but you can turn it off in the theme settings to try anyway

**Comment by bluebandit21** [comment]
I'm not certain what you're asking me with the first question. 
Turning off the visualizer within settings did not help, unfortunately.

**Comment by MinaciousGrace** [comment]
i suppose what i should have asked was what is the last version you were able to start the game successfully on?

**Comment by bluebandit21** [comment]
That makes sense.
To be honest, I haven't tried to build Etterna from source before. (I've been using the 65.1 OSX dmg)
It is entirely possible that it's not working because I've screwed up some step of the build process.

**Comment by bluebandit21** [comment]
Building 68.0 / 67.1 / 67.0 from source has the same issue.
I'll check if 66 works.

**Comment by bluebandit21** [comment]
Well, unfortunately I'm having the same issue with the 69.0 release. (Which is a shame, since I'm excited to see Wife V3)

Is there some sort of "debug mode" I can build it in to provide more helpful information to you?
If it's helpful as well, I can include the versions of all of the dependencies I have or any useful output from the build process. 

I can also tell you the complete step-by-step of how I'm attempting to build Etterna, in case I'm somehow doing something wrong.

**Comment by martensm** [comment]
This should be fixed as of #779 being merged, please reopen if that is not the case.

**Comment by bluebandit21** [comment]
I hate to say it, but that unfortunately did not fix the issue. 
I just built dbac6cf47a864dc54d7812eb018b87d4e20a3154 and it had the same problem as before.

**Comment by bluebandit21** [comment]
I also do not have the permissions to reopen this issue, so I can not reopen it myself.
Would you mind doing so?

**Comment by jameskr97** [comment]
@bluebandit21 Could you give me some of your system information, and most whatever logs you have? It would help me debug this.

**Comment by bluebandit21** [comment]
Sure. Here are all the logs from that build and run. (Which unfortunately don't say much)
[info.txt](https://github.com/etternagame/etterna/files/4679614/info.txt)
[log.txt](https://github.com/etternagame/etterna/files/4679615/log.txt)

What system information do you want?

**Comment by jameskr97** [comment]
System version number, please. The only way I have of debugging this is downloading macOS Mojave, since it works on catalina and high sierra. So, I would be downloading the Mojave version you have, or whatever it's latest version is.

**Comment by bluebandit21** [comment]
Wait, this is weird.
I tried launching that build again, and the second time it worked.
(The first run it had an issue in exactly the same way as it had earlier)
Who knows why it didn't work the first time, but I'm going to tentatively mark this issue as closed.

Thanks for all of the help

**Comment by jameskr97** [comment]
Be sure to clean the build directory and delete the binary when doing testing new changes!

Happy to help.

**Comment by bluebandit21** [comment]
Believe me, I've been cloning from source each time. 
I'm going to blame this one on computer gremlins.

**Comment by bluebandit21** [comment]
(Properly fixed by PR #791)
